import 'package:flutter/material.dart';
import 'package:dropdown_search/dropdown_search.dart';

import 'home_list.dart';
import 'home_scan.dart';

class ListPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        //   backgroundColor: Colors.grey.shade200,
        backgroundColor: Color(0xFFEDF2F6),
        appBar: PreferredSize(
          preferredSize: Size.fromHeight(90),
          child: HomeList(),
        ),
        body: Padding(
          padding: const EdgeInsets.all(20),
          child: ListView(
            children: [
              Row(
                children: [
                  //   Icon(
                  //    Icons.location_on,
                  //    color: Color(0xFFF65959),
                  //    ),
                  Text(
                    "Lantai 2",
                    style: TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ],
              ),
              Row(
                children: [
                  //   Icon(
                  //    Icons.location_on,
                  //    color: Color(0xFFF65959),
                  //    ),
                  Text(
                    "Lab komputer",
                    style: TextStyle(
                        fontSize: 13,
                        fontWeight: FontWeight.w500,
                        color: Colors.redAccent),
                  ),
                ],
              ),
              DropdownSearch<String>(
                popupProps: PopupProps.menu(
                  showSelectedItems: true,
                  disabledItemFn: (String s) => s.startsWith('I'),
                ),
                items: [
                  "KOMPUTER (Disabled)",
                  "ITBMDN. EL.KOMP.00001",
                  "ITBMDN. EL.KOMP.00002",
                  "ITBMDN. EL.KOMP.00003",
                  "ITBMDN. EL.KOMP.00004",
                  "ITBMDN. EL.KOMP.00005",
                  "ITBMDN. EL.KOMP.00006",
                  "ITBMDN. EL.KOMP.00007",
                  "ITBMDN. EL.KOMP.00008",
                  "ITBMDN. EL.KOMP.00009",
                  "ITBMDN. EL.KOMP.00010",
                  "ITBMDN. EL.KOMP.00011",
                  "ITBMDN. EL.KOMP.00012",
                  "ITBMDN. EL.KOMP.00013",
                  "ITBMDN. EL.KOMP.00014",
                  "ITBMDN. EL.KOMP.00015",
                  "ITBMDN. EL.KOMP.00016",
                  "PROYEKTOR (Disabled)",
                  "ITBMDN.EL.PRYTR.00001",
                  "AC (Disabled)",
                  "ITBMDN.EL.AC.00001",
                  "ITBMDN.EL.AC.00002",
                  "CCTV (Disabled)",
                  "ITBMDN.EL.CCTV.00001",
                  "LAMPU (Disabled)",
                  "ITBMDN.EL.LAMP.00001",
                  "ITBMDN.EL.LAMP.00002",
                  "ITBMDN.EL.LAMP.00003",
                  "ITBMDN.EL.LAMP.00004",
                  "KABEL HDMI (Disabled)",
                  "ITBMDN.EL.KBL.00001",
                  "STOP KONTAK (Disabled)",
                  "ITBMDN.EL.SK.00001",
                  "MEJA (Disabled)",
                  "ITBMDN.MB.MJ.00001",
                  "ITBMDN.MB.MJ.00002",
                  "ITBMDN.MB.MJ.00003",
                  "KURSI (Disabled)",
                  "ITBMDN.MB.KRS.00001",
                  "ITBMDN.MB.KRS.00002",
                  "ITBMDN.MB.KRS.00003",
                  "ITBMDN.MB.KRS.00004",
                  "ITBMDN.MB.KRS.00005",
                  "ITBMDN.MB.KRS.00006",
                  "ITBMDN.MB.KRS.00007",
                  "ITBMDN.MB.KRS.00008",
                  "ITBMDN.MB.KRS.00009",
                  "ITBMDN.MB.KRS.00010",
                  "ITBMDN.MB.KRS.00011",
                  "ITBMDN.MB.KRS.00012",
                  "ITBMDN.MB.KRS.00013",
                  "ITBMDN.MB.KRS.00014",
                  "ITBMDN.MB.KRS.00015",
                  "ITBMDN.MB.KRS.00016",
                  "ITBMDN.MB.KRS.00017",
                  "ITBMDN.MB.KRS.00018",
                  "ITBMDN.MB.KRS.00019",
                  "ITBMDN.MB.KRS.00020",
                  "ITBMDN.MB.KRS.00021",
                  "ITBMDN.MB.KRS.00022",
                  "ITBMDN.MB.KRS.00023",
                  "ITBMDN.MB.KRS.00024",
                  "ITBMDN.MB.KRS.00025",
                  "PAPAN TULIS (Disabled)",
                  "ITBMDN.MB.PPN.00001",
                ],
                dropdownDecoratorProps: DropDownDecoratorProps(
                  dropdownSearchDecoration: InputDecoration(
                    labelText: "Ruang I",
                    hintText: "country in menu mode",
                  ),
                ),
                onChanged: print,
                selectedItem: "Lihat Barang",
              ),
              SizedBox(height: 20),
              DropdownSearch<String>(
                popupProps: PopupProps.menu(
                  showSelectedItems: true,
                  disabledItemFn: (String s) => s.startsWith('I'),
                ),
                items: [
                  "KOMPUTER (Disabled)",
                  "ITBMDN. EL.KOMP.00001",
                  "ITBMDN. EL.KOMP.00002",
                  "ITBMDN. EL.KOMP.00003",
                  "ITBMDN. EL.KOMP.00004",
                  "ITBMDN. EL.KOMP.00005",
                  "ITBMDN. EL.KOMP.00006",
                  "ITBMDN. EL.KOMP.00007",
                  "ITBMDN. EL.KOMP.00008",
                  "ITBMDN. EL.KOMP.00009",
                  "ITBMDN. EL.KOMP.00010",
                  "ITBMDN. EL.KOMP.00011",
                  "ITBMDN. EL.KOMP.00012",
                  "ITBMDN. EL.KOMP.00013",
                  "PROYEKTOR (Disabled)",
                  "ITBMDN.EL.PRYTR.00001",
                  "AC (Disabled)",
                  "ITBMDN.EL.AC.00001",
                  "ITBMDN.EL.AC.00002",
                  "CCTV (Disabled)",
                  "ITBMDN.EL.CCTV.00001",
                  "LAMPU (Disabled)",
                  "ITBMDN.EL.LAMP.00001",
                  "ITBMDN.EL.LAMP.00002",
                  "ITBMDN.EL.LAMP.00003",
                  "ITBMDN.EL.LAMP.00004",
                  "KABEL HDMI (Disabled)",
                  "ITBMDN.EL.KBL.00001",
                  "STOP KONTAK (Disabled)",
                  "ITBMDN.EL.SK.00001",
                  "MEJA (Disabled)",
                  "ITBMDN.MB.MJ.00001",
                  "ITBMDN.MB.MJ.00002",
                  "KURSI (Disabled)",
                  "ITBMDN.MB.KRS.00001",
                  "ITBMDN.MB.KRS.00002",
                  "ITBMDN.MB.KRS.00003",
                  "ITBMDN.MB.KRS.00004",
                  "ITBMDN.MB.KRS.00005",
                  "ITBMDN.MB.KRS.00006",
                  "ITBMDN.MB.KRS.00007",
                  "ITBMDN.MB.KRS.00008",
                  "ITBMDN.MB.KRS.00009",
                  "ITBMDN.MB.KRS.00010",
                  "ITBMDN.MB.KRS.00011",
                  "PAPAN TULIS (Disabled)",
                  "ITBMDN.MB.PPN.00001",
                ],
                dropdownDecoratorProps: DropDownDecoratorProps(
                  dropdownSearchDecoration: InputDecoration(
                    labelText: "Ruang II",
                    hintText: "country in menu mode",
                  ),
                ),
                onChanged: print,
                selectedItem: "Lihat Barang",
              ),
              SizedBox(height: 20),
              Row(
                children: [
                  //   Icon(
                  //    Icons.location_on,
                  //    color: Color(0xFFF65959),
                  //    ),
                  Text(
                    "Lantai 3",
                    style: TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ],
              ),
              Row(
                children: [
                  //   Icon(
                  //    Icons.location_on,
                  //    color: Color(0xFFF65959),
                  //    ),
                  Text(
                    "Lab komputer",
                    style: TextStyle(
                        fontSize: 13,
                        fontWeight: FontWeight.w500,
                        color: Colors.redAccent),
                  ),
                ],
              ),
              DropdownSearch<String>(
                popupProps: PopupProps.menu(
                  showSelectedItems: true,
                  disabledItemFn: (String s) => s.startsWith('I'),
                ),
                items: [
                  "KOMPUTER (Disabled)",
                  "ITBMDN. EL.KOMP.00001",
                  "ITBMDN. EL.KOMP.00002",
                  "ITBMDN. EL.KOMP.00003",
                  "ITBMDN. EL.KOMP.00004",
                  "ITBMDN. EL.KOMP.00005",
                  "ITBMDN. EL.KOMP.00006",
                  "ITBMDN. EL.KOMP.00007",
                  "ITBMDN. EL.KOMP.00008",
                  "ITBMDN. EL.KOMP.00009",
                  "ITBMDN. EL.KOMP.00010",
                  "ITBMDN. EL.KOMP.00011",
                  "ITBMDN. EL.KOMP.00012",
                  "ITBMDN. EL.KOMP.00013",
                  "ITBMDN. EL.KOMP.00014",
                  "PROYEKTOR (Disabled)",
                  "ITBMDN.EL.PRYTR.00001",
                  "AC (Disabled)",
                  "ITBMDN.EL.AC.00001",
                  "ITBMDN.EL.AC.00002",
                  "CCTV (Disabled)",
                  "ITBMDN.EL.CCTV.00001",
                  "LAMPU (Disabled)",
                  "ITBMDN.EL.LAMP.00001",
                  "ITBMDN.EL.LAMP.00002",
                  "ITBMDN.EL.LAMP.00003",
                  "ITBMDN.EL.LAMP.00004",
                  "KABEL HDMI (Disabled)",
                  "ITBMDN.EL.KBL.00001",
                  "STOP KONTAK (Disabled)",
                  "ITBMDN.EL.SK.00001",
                  "MEJA (Disabled)",
                  "ITBMDN.MB.MJ.00001",
                  "ITBMDN.MB.MJ.00002",
                  "ITBMDN.MB.MJ.00003",
                  "ITBMDN.MB.MJ.00004",
                  "ITBMDN.MB.MJ.00005",
                  "ITBMDN.MB.MJ.00006",
                  "ITBMDN.MB.MJ.00007",
                  "ITBMDN.MB.MJ.00008",
                  "ITBMDN.MB.MJ.00009",
                  "ITBMDN.MB.MJ.00010",
                  "ITBMDN.MB.MJ.00011",
                  "ITBMDN.MB.MJ.00012",
                  "ITBMDN.MB.MJ.00013",
                  "ITBMDN.MB.MJ.00014",
                  "PAPAN TULIS (Disabled)",
                  "ITBMDN.MB.PPN.00001",
                ],
                dropdownDecoratorProps: DropDownDecoratorProps(
                  dropdownSearchDecoration: InputDecoration(
                    labelText: "Ruang I",
                    hintText: "country in menu mode",
                  ),
                ),
                onChanged: print,
                selectedItem: "Lihat Barang",
              ),
              SizedBox(height: 20),
              DropdownSearch<String>(
                popupProps: PopupProps.menu(
                  showSelectedItems: true,
                  disabledItemFn: (String s) => s.startsWith('I'),
                ),
                items: [
                  "KOMPUTER (Disabled)",
                  "ITBMDN. EL.KOMP.00001",
                  "ITBMDN. EL.KOMP.00002",
                  "ITBMDN. EL.KOMP.00003",
                  "ITBMDN. EL.KOMP.00004",
                  "ITBMDN. EL.KOMP.00005",
                  "ITBMDN. EL.KOMP.00006",
                  "ITBMDN. EL.KOMP.00007",
                  "ITBMDN. EL.KOMP.00008",
                  "ITBMDN. EL.KOMP.00009",
                  "ITBMDN. EL.KOMP.00010",
                  "ITBMDN. EL.KOMP.00011",
                  "ITBMDN. EL.KOMP.00012",
                  "PROYEKTOR (Disabled)",
                  "ITBMDN.EL.PRYTR.00001",
                  "AC (Disabled)",
                  "ITBMDN.EL.AC.00001",
                  "ITBMDN.EL.AC.00002",
                  "CCTV (Disabled)",
                  "ITBMDN.EL.CCTV.00001",
                  "LAMPU (Disabled)",
                  "ITBMDN.EL.LAMP.00001",
                  "ITBMDN.EL.LAMP.00002",
                  "ITBMDN.EL.LAMP.00003",
                  "ITBMDN.EL.LAMP.00004",
                  "KABEL HDMI (Disabled)",
                  "ITBMDN.EL.KBL.00001",
                  "STOP KONTAK (Disabled)",
                  "ITBMDN.EL.SK.00001",
                  "MEJA (Disabled)",
                  "ITBMDN.MB.MJ.00001",
                  "ITBMDN.MB.MJ.00002",
                  "KURSI (Disabled)",
                  "ITBMDN.MB.KRS.00001",
                  "ITBMDN.MB.KRS.00002",
                  "ITBMDN.MB.KRS.00003",
                  "ITBMDN.MB.KRS.00004",
                  "PAPAN TULIS (Disabled)",
                  "ITBMDN.MB.PPN.00001",
                ],
                dropdownDecoratorProps: DropDownDecoratorProps(
                  dropdownSearchDecoration: InputDecoration(
                    labelText: "Ruang II",
                    hintText: "country in menu mode",
                  ),
                ),
                onChanged: print,
                selectedItem: "Lihat Barang",
              ),
              SizedBox(height: 20),
              Row(
                children: [
                  //   Icon(
                  //    Icons.location_on,
                  //    color: Color(0xFFF65959),
                  //    ),
                  Text(
                    "Lantai 2",
                    style: TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ],
              ),
              Row(
                children: [
                  //   Icon(
                  //    Icons.location_on,
                  //    color: Color(0xFFF65959),
                  //    ),
                  Text(
                    "Ruang Kelas",
                    style: TextStyle(
                        fontSize: 13,
                        fontWeight: FontWeight.w500,
                        color: Colors.redAccent),
                  ),
                ],
              ),
              DropdownSearch<String>(
                popupProps: PopupProps.menu(
                  showSelectedItems: true,
                  disabledItemFn: (String s) => s.startsWith('I'),
                ),
                items: [
                  "KURSI (Disabled)",
                  "ITBMDN.MB.KRS.00001",
                  "ITBMDN.MB.KRS.00002",
                  "ITBMDN.MB.KRS.00003",
                  "ITBMDN.MB.KRS.00004",
                  "ITBMDN.MB.KRS.00005",
                  "ITBMDN.MB.KRS.00006",
                  "ITBMDN.MB.KRS.00007",
                  "ITBMDN.MB.KRS.00008",
                  "ITBMDN.MB.KRS.00009",
                  "ITBMDN.MB.KRS.00010",
                  "ITBMDN.MB.KRS.00011",
                  "ITBMDN.MB.KRS.00012",
                  "ITBMDN.MB.KRS.00013",
                  "ITBMDN.MB.KRS.00014",
                  "ITBMDN.MB.KRS.00015",
                  "ITBMDN.MB.KRS.00016",
                  "ITBMDN.MB.KRS.00017",
                  "ITBMDN.MB.KRS.00018",
                  "ITBMDN.MB.KRS.00019",
                  "ITBMDN.MB.KRS.00020",
                  "ITBMDN.MB.KRS.00021",
                  "ITBMDN.MB.KRS.00022",
                  "ITBMDN.MB.KRS.00023",
                  "ITBMDN.MB.KRS.00024",
                  "ITBMDN.MB.KRS.00025",
                  "ITBMDN.MB.KRS.000026",
                  "ITBMDN.MB.KRS.000027",
                  "ITBMDN.MB.KRS.000028",
                  "ITBMDN.MB.KRS.000029",
                  "ITBMDN.MB.KRS.000030",
                  "ITBMDN.MB.KRS.000031",
                  "ITBMDN.MB.KRS.000032",
                  "ITBMDN.MB.KRS.000033",
                  "ITBMDN.MB.KRS.000034",
                  "ITBMDN.MB.KRS.00035",
                  "ITBMDN.MB.KRS.00036",
                  "ITBMDN.MB.KRS.00037",
                  "ITBMDN.MB.KRS.00038",
                  "ITBMDN.MB.KRS.00039",
                  "ITBMDN.MB.KRS.00040",
                  "ITBMDN.MB.KRS.00041",
                  "ITBMDN.MB.KRS.00042",
                  "ITBMDN.MB.KRS.00042",
                  "ITBMDN.MB.KRS.00043",
                  "ITBMDN.MB.KRS.00044",
                  "ITBMDN.MB.KRS.00045",
                  "ITBMDN.MB.KRS.00046",
                  "ITBMDN.MB.KRS.00047",
                  "ITBMDN.MB.KRS.00048",
                  "ITBMDN.MB.KRS.00049",
                  "ITBMDN.MB.KRS.00050",
                  "ITBMDN.MB.KRS.00051",
                  "ITBMDN.MB.KRS.00052",
                  "ITBMDN.MB.KRS.00053",
                  "ITBMDN.MB.KRS.00054",
                  "ITBMDN.MB.KRS.00055",
                  "ITBMDN.MB.KRS.00056",
                  "ITBMDN.MB.KRS.00057",
                  "ITBMDN.MB.KRS.00058",
                  "ITBMDN.MB.KRS.00059",
                  "ITBMDN.MB.KRS.00060",
                  "ITBMDN.MB.KRS.00061",
                  "ITBMDN.MB.KRS.00062",
                  "ITBMDN.MB.KRS.00063",
                  "ITBMDN.MB.KRS.00064",
                  "ITBMDN.MB.KRS.00065",
                  "ITBMDN.MB.KRS.00066",
                  "ITBMDN.MB.KRS.00067",
                  "ITBMDN.MB.KRS.00068",
                  "ITBMDN.MB.KRS.00069",
                  "ITBMDN.MB.KRS.00070",
                  "ITBMDN.MB.KRS.00071",
                  "ITBMDN.MB.KRS.00072",
                  "ITBMDN.MB.KRS.00073",
                  "ITBMDN.MB.KRS.00074",
                  "ITBMDN.MB.KRS.00075",
                  "ITBMDN.MB.KRS.00076",
                  "ITBMDN.MB.KRS.00077",
                  "ITBMDN.MB.KRS.00078",
                  "ITBMDN.MB.KRS.00079",
                  "ITBMDN.MB.KRS.00080",
                  "ITBMDN.MB.KRS.00081",
                  "ITBMDN.MB.KRS.00082",
                  "ITBMDN.MB.KRS.00083",
                  "ITBMDN.MB.KRS.00084",
                  "ITBMDN.MB.KRS.00085",
                  "ITBMDN.MB.KRS.00086",
                  "ITBMDN.MB.KRS.00087",
                  "ITBMDN.MB.KRS.00088",
                  "ITBMDN.MB.KRS.00089",
                  "ITBMDN.MB.KRS.00090",
                  "ITBMDN.MB.KRS.00091",
                  "ITBMDN.MB.KRS.00092",
                  "ITBMDN.MB.KRS.00093",
                  "ITBMDN.MB.KRS.00094",
                  "LAMPU (Disabled)",
                  "ITBMDN.EL.LAMP.00001",
                  "ITBMDN.EL.LAMP.00002",
                  "ITBMDN.EL.LAMP.00003",
                  "ITBMDN.EL.LAMP.00004",
                  "ITBMDN.EL.LAMP.00005",
                  "ITBMDN.EL.LAMP.00006",
                  "ITBMDN.EL.LAMP.00007",
                  "ITBMDN.EL.LAMP.00008",
                  "ITBMDN.EL.LAMP.00009",
                  "ITBMDN.EL.LAMP.000010",
                  "ITBMDN.EL.LAMP.000011",
                  "ITBMDN.EL.LAMP.000012",
                  "ITBMDN.EL.LAMP.000013",
                  "ITBMDN.EL.LAMP.000014",
                  "ITBMDN.EL.LAMP.000015",
                  "ITBMDN.EL.LAMP.000016",
                  "ITBMDN.EL.LAMP.000017",
                  "ITBMDN.EL.LAMP.000018",
                  "ITBMDN.EL.LAMP.000019",
                  "ITBMDN.EL.LAMP.000020",
                  "ITBMDN.EL.LAMP.000021",
                  "ITBMDN.EL.LAMP.000022",
                  "ITBMDN.EL.LAMP.000023",
                  "ITBMDN.EL.LAMP.000024",
                  "ITBMDN.EL.LAMP.000025",
                  "ITBMDN.EL.LAMP.000026",
                  "ITBMDN.EL.LAMP.000027",
                  "ITBMDN.EL.LAMP.000028",
                  "ITBMDN.EL.LAMP.000029",
                  "ITBMDN.EL.LAMP.000030",
                  "CCTV (Disabled)",
                  "ITBMDN.EL.CCTV.00001",
                  "PROYEKTOR (Disabled)",
                  "ITBMDN.EL.PRYTR.00001",
                  "KIPAS ANGIN (Disabled)",
                  "ITBMDN.EL.KPS.00001",
                  "ITBMDN.EL.KPS.00002",
                  "ITBMDN.EL.KPS.00003",
                  "PAPAN TULIS (Disabled)",
                  "ITBMDN.MB.PPN.00001",
                  "MEJA (Disabled)",
                  "ITBMDN.MB.MJ.00001",
                ],
                dropdownDecoratorProps: DropDownDecoratorProps(
                  dropdownSearchDecoration: InputDecoration(
                    labelText: "R1",
                    hintText: "country in menu mode",
                  ),
                ),
                onChanged: print,
                selectedItem: "Lihat Barang",
              ),
              SizedBox(height: 20),
              Row(
                children: [
                  //   Icon(
                  //    Icons.location_on,
                  //    color: Color(0xFFF65959),
                  //    ),
                  Text(
                    "Lantai 3",
                    style: TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ],
              ),
              Row(
                children: [
                  //   Icon(
                  //    Icons.location_on,
                  //    color: Color(0xFFF65959),
                  //    ),
                  Text(
                    "Ruang Kelas",
                    style: TextStyle(
                        fontSize: 13,
                        fontWeight: FontWeight.w500,
                        color: Colors.redAccent),
                  ),
                ],
              ),
              DropdownSearch<String>(
                popupProps: PopupProps.menu(
                  showSelectedItems: true,
                  disabledItemFn: (String s) => s.startsWith('I'),
                ),
                items: [
                  "KURSI (Disabled)",
                  "ITBMDN.MB.KRS.00001",
                  "ITBMDN.MB.KRS.00002",
                  "ITBMDN.MB.KRS.00003",
                  "ITBMDN.MB.KRS.00004",
                  "ITBMDN.MB.KRS.00005",
                  "ITBMDN.MB.KRS.00006",
                  "ITBMDN.MB.KRS.00007",
                  "ITBMDN.MB.KRS.00008",
                  "ITBMDN.MB.KRS.00009",
                  "ITBMDN.MB.KRS.00010",
                  "ITBMDN.MB.KRS.00011",
                  "ITBMDN.MB.KRS.00012",
                  "ITBMDN.MB.KRS.00013",
                  "ITBMDN.MB.KRS.00014",
                  "ITBMDN.MB.KRS.00015",
                  "ITBMDN.MB.KRS.00016",
                  "ITBMDN.MB.KRS.00017",
                  "ITBMDN.MB.KRS.00018",
                  "ITBMDN.MB.KRS.00019",
                  "ITBMDN.MB.KRS.00020",
                  "ITBMDN.MB.KRS.00021",
                  "ITBMDN.MB.KRS.00022",
                  "ITBMDN.MB.KRS.00023",
                  "ITBMDN.MB.KRS.00024",
                  "ITBMDN.MB.KRS.00025",
                  "ITBMDN.MB.KRS.000026",
                  "ITBMDN.MB.KRS.000027",
                  "ITBMDN.MB.KRS.000028",
                  "ITBMDN.MB.KRS.000029",
                  "ITBMDN.MB.KRS.000030",
                  "ITBMDN.MB.KRS.000031",
                  "ITBMDN.MB.KRS.000032",
                  "ITBMDN.MB.KRS.000033",
                  "ITBMDN.MB.KRS.000034",
                  "ITBMDN.MB.KRS.00035",
                  "ITBMDN.MB.KRS.00036",
                  "ITBMDN.MB.KRS.00037",
                  "ITBMDN.MB.KRS.00038",
                  "LAMPU (Disabled)",
                  "ITBMDN.EL.LAMP.00001",
                  "ITBMDN.EL.LAMP.00002",
                  "PROYEKTOR (Disabled)",
                  "ITBMDN.EL.PRYTR.00001",
                  "KIPAS ANGIN (Disabled)",
                  "ITBMDN.EL.KPS.00001",
                  "PAPAN TULIS (Disabled)",
                  "ITBMDN.MB.PPN.00001",
                  "MEJA (Disabled)",
                  "ITBMDN.MB.MJ.00001",
                ],
                dropdownDecoratorProps: DropDownDecoratorProps(
                  dropdownSearchDecoration: InputDecoration(
                    labelText: "R3",
                    hintText: "country in menu mode",
                  ),
                ),
                onChanged: print,
                selectedItem: "Lihat Barang",
              ),
              SizedBox(height: 20),
              DropdownSearch<String>(
                popupProps: PopupProps.menu(
                  showSelectedItems: true,
                  disabledItemFn: (String s) => s.startsWith('I'),
                ),
                items: [
                  "KURSI (Disabled)",
                  "ITBMDN.MB.KRS.00001",
                  "ITBMDN.MB.KRS.00002",
                  "ITBMDN.MB.KRS.00003",
                  "ITBMDN.MB.KRS.00004",
                  "ITBMDN.MB.KRS.00005",
                  "ITBMDN.MB.KRS.00006",
                  "ITBMDN.MB.KRS.00007",
                  "ITBMDN.MB.KRS.00008",
                  "ITBMDN.MB.KRS.00009",
                  "ITBMDN.MB.KRS.00010",
                  "ITBMDN.MB.KRS.00011",
                  "ITBMDN.MB.KRS.00012",
                  "ITBMDN.MB.KRS.00013",
                  "ITBMDN.MB.KRS.00014",
                  "ITBMDN.MB.KRS.00015",
                  "ITBMDN.MB.KRS.00016",
                  "ITBMDN.MB.KRS.00017",
                  "ITBMDN.MB.KRS.00018",
                  "ITBMDN.MB.KRS.00019",
                  "ITBMDN.MB.KRS.00020",
                  "ITBMDN.MB.KRS.00021",
                  "ITBMDN.MB.KRS.00022",
                  "ITBMDN.MB.KRS.00023",
                  "ITBMDN.MB.KRS.00024",
                  "ITBMDN.MB.KRS.00025",
                  "ITBMDN.MB.KRS.000026",
                  "ITBMDN.MB.KRS.000027",
                  "ITBMDN.MB.KRS.000028",
                  "ITBMDN.MB.KRS.000029",
                  "ITBMDN.MB.KRS.000030",
                  "ITBMDN.MB.KRS.000031",
                  "ITBMDN.MB.KRS.000032",
                  "ITBMDN.MB.KRS.000033",
                  "ITBMDN.MB.KRS.000034",
                  "ITBMDN.MB.KRS.00035",
                  "ITBMDN.MB.KRS.00036",
                  "ITBMDN.MB.KRS.00037",
                  "ITBMDN.MB.KRS.00038",
                  "ITBMDN.MB.KRS.00039",
                  "ITBMDN.MB.KRS.00040",
                  "ITBMDN.MB.KRS.00041",
                  "ITBMDN.MB.KRS.00042",
                  "ITBMDN.MB.KRS.00042",
                  "ITBMDN.MB.KRS.00043",
                  "ITBMDN.MB.KRS.00044",
                  "ITBMDN.MB.KRS.00045",
                  "ITBMDN.MB.KRS.00046",
                  "ITBMDN.MB.KRS.00047",
                  "ITBMDN.MB.KRS.00048",
                  "ITBMDN.MB.KRS.00049",
                  "ITBMDN.MB.KRS.00050",
                  "ITBMDN.MB.KRS.00051",
                  "ITBMDN.MB.KRS.00052",
                  "ITBMDN.MB.KRS.00053",
                  "ITBMDN.MB.KRS.00054",
                  "ITBMDN.MB.KRS.00055",
                  "ITBMDN.MB.KRS.00056",
                  "ITBMDN.MB.KRS.00057",
                  "ITBMDN.MB.KRS.00058",
                  "ITBMDN.MB.KRS.00059",
                  "ITBMDN.MB.KRS.00060",
                  "ITBMDN.MB.KRS.00061",
                  "ITBMDN.MB.KRS.00062",
                  "ITBMDN.MB.KRS.00063",
                  "ITBMDN.MB.KRS.00064",
                  "ITBMDN.MB.KRS.00065",
                  "ITBMDN.MB.KRS.00066",
                  "ITBMDN.MB.KRS.00067",
                  "ITBMDN.MB.KRS.00068",
                  "ITBMDN.MB.KRS.00069",
                  "ITBMDN.MB.KRS.00070",
                  "ITBMDN.MB.KRS.00071",
                  "ITBMDN.MB.KRS.00072",
                  "ITBMDN.MB.KRS.00073",
                  "ITBMDN.MB.KRS.00074",
                  "ITBMDN.MB.KRS.00075",
                  "ITBMDN.MB.KRS.00076",
                  "ITBMDN.MB.KRS.00077",
                  "ITBMDN.MB.KRS.00078",
                  "ITBMDN.MB.KRS.00079",
                  "ITBMDN.MB.KRS.00080",
                  "ITBMDN.MB.KRS.00081",
                  "ITBMDN.MB.KRS.00082",
                  "ITBMDN.MB.KRS.00083",
                  "ITBMDN.MB.KRS.00084",
                  "ITBMDN.MB.KRS.00085",
                  "ITBMDN.MB.KRS.00086",
                  "ITBMDN.MB.KRS.00087",
                  "ITBMDN.MB.KRS.00088",
                  "ITBMDN.MB.KRS.00089",
                  "ITBMDN.MB.KRS.00090",
                  "ITBMDN.MB.KRS.00091",
                  "ITBMDN.MB.KRS.00092",
                  "ITBMDN.MB.KRS.00093",
                  "ITBMDN.MB.KRS.00094",
                  "ITBMDN.MB.KRS.00095",
                  "ITBMDN.MB.KRS.00096",
                  "ITBMDN.MB.KRS.00097",
                  "ITBMDN.MB.KRS.00098",
                  "LAMPU (Disabled)",
                  "ITBMDN.EL.LAMP.00001",
                  "ITBMDN.EL.LAMP.00002",
                  "ITBMDN.EL.LAMP.00003",
                  "ITBMDN.EL.LAMP.00004",
                  "ITBMDN.EL.LAMP.00005",
                  "ITBMDN.EL.LAMP.00006",
                  "ITBMDN.EL.LAMP.00007",
                  "ITBMDN.EL.LAMP.00008",
                  "ITBMDN.EL.LAMP.00009",
                  "ITBMDN.EL.LAMP.000010",
                  "ITBMDN.EL.LAMP.000011",
                  "ITBMDN.EL.LAMP.000012",
                  "ITBMDN.EL.LAMP.000013",
                  "ITBMDN.EL.LAMP.000014",
                  "ITBMDN.EL.LAMP.000015",
                  "ITBMDN.EL.LAMP.000016",
                  "ITBMDN.EL.LAMP.000017",
                  "ITBMDN.EL.LAMP.000018",
                  "ITBMDN.EL.LAMP.000019",
                  "ITBMDN.EL.LAMP.000020",
                  "ITBMDN.EL.LAMP.000021",
                  "ITBMDN.EL.LAMP.000022",
                  "ITBMDN.EL.LAMP.000023",
                  "ITBMDN.EL.LAMP.000024",
                  "ITBMDN.EL.LAMP.000025",
                  "ITBMDN.EL.LAMP.000026",
                  "ITBMDN.EL.LAMP.000027",
                  "ITBMDN.EL.LAMP.000028",
                  "ITBMDN.EL.LAMP.000029",
                  "ITBMDN.EL.LAMP.000030",
                  "CCTV (Disabled)",
                  "ITBMDN.EL.CCTV.00001",
                  "PROYEKTOR (Disabled)",
                  "ITBMDN.EL.PRYTR.00001",
                  "KIPAS ANGIN (Disabled)",
                  "ITBMDN.EL.KPS.00001",
                  "ITBMDN.EL.KPS.00002",
                  "ITBMDN.EL.KPS.00003",
                  "ITBMDN.EL.KPS.00004",
                  "PAPAN TULIS (Disabled)",
                  "ITBMDN.MB.PPN.00001",
                  "STOP KONTAK (Disabled)",
                  "ITBMDN.EL.SK.00001",
                  "ITBMDN.EL.SK.00002",
                  "ITBMDN.EL.SK.00003",
                  "ITBMDN.EL.SK.00004",
                  "ITBMDN.EL.SK.00005",
                  "MEJA (Disabled)",
                  "ITBMDN.MB.MJ.00001",
                  "ITBMDN.MB.MJ.00002",
                  "ITBMDN.MB.MJ.00003",
                  "ITBMDN.MB.MJ.00004",
                  "ITBMDN.MB.MJ.00005",
                  "ITBMDN.MB.MJ.00006",
                  "ITBMDN.MB.MJ.00007",
                  "ITBMDN.MB.MJ.00008",
                  "ITBMDN.MB.MJ.00009",
                  "ITBMDN.MB.MJ.00010",
                  "ITBMDN.MB.MJ.00011",
                  "ITBMDN.MB.MJ.00012",
                  "ITBMDN.MB.MJ.00013",
                  "ITBMDN.MB.MJ.00014",
                  "ITBMDN.MB.MJ.000015",
                  "ITBMDN.MB.MJ.000016",
                  "ITBMDN.MB.MJ.000017",
                  "ITBMDN.MB.MJ.000018",
                  "ITBMDN.MB.MJ.000019",
                  "ITBMDN.MB.MJ.000020",
                  "ITBMDN.MB.MJ.000021",
                  "ITBMDN.MB.MJ.000022",
                  "ITBMDN.MB.MJ.000023",
                  "ITBMDN.MB.MJ.00024",
                  "ITBMDN.MB.MJ.00025",
                  "ITBMDN.MB.MJ.00026",
                  "ITBMDN.MB.MJ.00027",
                  "ITBMDN.MB.MJ.00028",
                  "ITBMDN.MB.MJ.000029",
                  "ITBMDN.MB.MJ.000030",
                  "ITBMDN.MB.MJ.000031",
                  "ITBMDN.MB.MJ.00031",
                  "ITBMDN.MB.MJ.00032",
                  "ITBMDN.MB.MJ.00033",
                  "ITBMDN.MB.MJ.00034",
                  "ITBMDN.MB.MJ.00035",
                  "ITBMDN.MB.MJ.000036",
                  "ITBMDN.MB.MJ.000037",
                  "ITBMDN.MB.MJ.000038",
                  "ITBMDN.MB.MJ.00039",
                  "ITBMDN.MB.MJ.00040",
                  "ITBMDN.MB.MJ.00041",
                  "ITBMDN.MB.MJ.00042",
                  "ITBMDN.MB.MJ.00043",
                  "ITBMDN.MB.MJ.00044",
                  "ITBMDN.MB.MJ.00045",
                ],
                dropdownDecoratorProps: DropDownDecoratorProps(
                  dropdownSearchDecoration: InputDecoration(
                    labelText: "R2",
                    hintText: "country in menu mode",
                  ),
                ),
                onChanged: print,
                selectedItem: "Lihat Barang",
              ),
              SizedBox(height: 20),
              Row(
                children: [
                  //   Icon(
                  //    Icons.location_on,
                  //    color: Color(0xFFF65959),
                  //    ),
                  Text(
                    "Lantai 4",
                    style: TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ],
              ),
              Row(
                children: [
                  //   Icon(
                  //    Icons.location_on,
                  //    color: Color(0xFFF65959),
                  //    ),
                  Text(
                    "Ruang Kelas",
                    style: TextStyle(
                        fontSize: 13,
                        fontWeight: FontWeight.w500,
                        color: Colors.redAccent),
                  ),
                ],
              ),
              DropdownSearch<String>(
                popupProps: PopupProps.menu(
                  showSelectedItems: true,
                  disabledItemFn: (String s) => s.startsWith('I'),
                ),
                items: [
                  "KURSI (Disabled)",
                  "ITBMDN.MB.KRS.00001",
                  "ITBMDN.MB.KRS.00002",
                  "ITBMDN.MB.KRS.00003",
                  "ITBMDN.MB.KRS.00004",
                  "ITBMDN.MB.KRS.00005",
                  "ITBMDN.MB.KRS.00006",
                  "ITBMDN.MB.KRS.00007",
                  "ITBMDN.MB.KRS.00008",
                  "ITBMDN.MB.KRS.00009",
                  "ITBMDN.MB.KRS.00010",
                  "ITBMDN.MB.KRS.00011",
                  "ITBMDN.MB.KRS.00012",
                  "ITBMDN.MB.KRS.00013",
                  "ITBMDN.MB.KRS.00014",
                  "ITBMDN.MB.KRS.00015",
                  "ITBMDN.MB.KRS.00016",
                  "ITBMDN.MB.KRS.00017",
                  "ITBMDN.MB.KRS.00018",
                  "ITBMDN.MB.KRS.00019",
                  "ITBMDN.MB.KRS.00020",
                  "ITBMDN.MB.KRS.00021",
                  "ITBMDN.MB.KRS.00022",
                  "ITBMDN.MB.KRS.00023",
                  "ITBMDN.MB.KRS.00024",
                  "ITBMDN.MB.KRS.00025",
                  "ITBMDN.MB.KRS.000026",
                  "ITBMDN.MB.KRS.000027",
                  "ITBMDN.MB.KRS.000028",
                  "ITBMDN.MB.KRS.000029",
                  "ITBMDN.MB.KRS.000030",
                  "ITBMDN.MB.KRS.000031",
                  "ITBMDN.MB.KRS.000032",
                  "ITBMDN.MB.KRS.000033",
                  "ITBMDN.MB.KRS.000034",
                  "ITBMDN.MB.KRS.00035",
                  "ITBMDN.MB.KRS.00036",
                  "ITBMDN.MB.KRS.00037",
                  "ITBMDN.MB.KRS.00038",
                  "ITBMDN.MB.KRS.00039",
                  "ITBMDN.MB.KRS.00040",
                  "ITBMDN.MB.KRS.00041",
                  "ITBMDN.MB.KRS.00042",
                  "ITBMDN.MB.KRS.00042",
                  "ITBMDN.MB.KRS.00043",
                  "ITBMDN.MB.KRS.00044",
                  "ITBMDN.MB.KRS.00045",
                  "ITBMDN.MB.KRS.00046",
                  "ITBMDN.MB.KRS.00047",
                  "ITBMDN.MB.KRS.00048",
                  "ITBMDN.MB.KRS.00049",
                  "ITBMDN.MB.KRS.00050",
                  "ITBMDN.MB.KRS.00051",
                  "ITBMDN.MB.KRS.00052",
                  "ITBMDN.MB.KRS.00053",
                  "ITBMDN.MB.KRS.00054",
                  "ITBMDN.MB.KRS.00055",
                  "ITBMDN.MB.KRS.00056",
                  "ITBMDN.MB.KRS.00057",
                  "ITBMDN.MB.KRS.00058",
                  "ITBMDN.MB.KRS.00059",
                  "ITBMDN.MB.KRS.00060",
                  "ITBMDN.MB.KRS.00061",
                  "ITBMDN.MB.KRS.00062",
                  "ITBMDN.MB.KRS.00063",
                  "ITBMDN.MB.KRS.00064",
                  "ITBMDN.MB.KRS.00065",
                  "ITBMDN.MB.KRS.00066",
                  "ITBMDN.MB.KRS.00067",
                  "ITBMDN.MB.KRS.00068",
                  "ITBMDN.MB.KRS.00069",
                  "ITBMDN.MB.KRS.00070",
                  "ITBMDN.MB.KRS.00071",
                  "ITBMDN.MB.KRS.00072",
                  "ITBMDN.MB.KRS.00073",
                  "ITBMDN.MB.KRS.00074",
                  "ITBMDN.MB.KRS.00075",
                  "ITBMDN.MB.KRS.00076",
                  "ITBMDN.MB.KRS.00077",
                  "ITBMDN.MB.KRS.00078",
                  "LAMPU (Disabled)",
                  "ITBMDN.EL.LAMP.00001",
                  "ITBMDN.EL.LAMP.00002",
                  "ITBMDN.EL.LAMP.00003",
                  "ITBMDN.EL.LAMP.00004",
                  "ITBMDN.EL.LAMP.00005",
                  "ITBMDN.EL.LAMP.00006",
                  "ITBMDN.EL.LAMP.00007",
                  "ITBMDN.EL.LAMP.00008",
                  "CCTV (Disabled)",
                  "ITBMDN.EL.CCTV.00001",
                  "PROYEKTOR (Disabled)",
                  "ITBMDN.EL.PRYTR.00001",
                  "KIPAS ANGIN (Disabled)",
                  "ITBMDN.EL.KPS.00001",
                  "ITBMDN.EL.KPS.00002",
                  "ITBMDN.EL.KPS.00003",
                  "PAPAN TULIS (Disabled)",
                  "ITBMDN.MB.PPN.00001",
                  "STOP KONTAK (Disabled)",
                  "ITBMDN.EL.SK.00001",
                  "ITBMDN.EL.SK.00002",
                  "MEJA (Disabled)",
                  "ITBMDN.MB.MJ.00001",
                  "ITBMDN.MB.MJ.00002",
                  "ITBMDN.MB.MJ.00003",
                  "ITBMDN.MB.MJ.00004",
                  "PAPAN TULIS (Disabled)",
                  "ITBMDN.MB.PPN.00001",
                  "ITBMDN.MB.PPN.00002",
                  "SPEAKER (Disabled)",
                  "ITBMDN.EL.SPKR.00001",
                  "ITBMDN.EL.SPKR.00002",
                  "ITBMDN.EL.SPKR.00003",
                  "ITBMDN.EL.SPKR.00004",
                  "ITBMDN.EL.SPKR.00005",
                  "ITBMDN.EL.SPKR.00006",
                ],
                dropdownDecoratorProps: DropDownDecoratorProps(
                  dropdownSearchDecoration: InputDecoration(
                    labelText: "R4",
                    hintText: "country in menu mode",
                  ),
                ),
                onChanged: print,
                selectedItem: "Lihat Barang",
              ),
            ],
          ),
        ),
      );
}

bool isItemDisabled(String s) {
  if (s.startsWith('I')) {
    return true;
  } else {
    return false;
  }
}

void itemSelecionChanged(String? s) {}
